### ISSUE TITLE
Read Buffered Error - No Reset Method

### ISSUE THREAD

**Issue by knoxberry** [LabVIEW-DCAF/ExecutionInterface#33]
Hi all,

I'm currently trying to restart the DCAF engine in the event of an engine failure. In my case, an error with the scan engine has caused the timing in the primary control loop of the standard engine to fail and produce an error. In this case, the error gets propagated properly to the execution interface and I can call the stop and start methods. However, the read buffered error will report the last error the engine reported even after successfully starting and stopping the engine without error. There should be a way to reset this method.

If there is another recommended way of restarting the engine please let me know!

**Comment by becega** [comment]
Hi knoxberry
 Managing the errors and Faults is different in DCAF. In the case of the faults they are stored in a array and we do need to to have a clear faults VI, which is also in the pallets. 
With the errors, we are using a queue and the problem is it has a shift register that if the queue times out, it passes the error out. So more than an extra Vi we just need to add a reset input to this VI.
![image](https://user-images.githubusercontent.com/5290634/36916729-66e362f4-1e1a-11e8-919d-a9988f289d8e.png)
